In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('Multi-GAS data.csv', index_col=0, low_memory=False)

In [4]:
df.columns

Index(['Time', 'Status flag', 'Instrument temperature',
       'Air relative humidity', 'Air pressure', 'Sample pressure',
       'Mean horizontal wind speed', 'Mean horizontal wind direction',
       'H2O mixing ratio', 'CO2 mixing ratio', 'SO2 mixing ratio',
       'H2S mixing ratio'],
      dtype='object')

In [5]:
dfnew=df.iloc[:,[0,2]]

In [6]:
dfnew

             Time Instrument temperature
Date
NaN           UTC        degrees Celsius
5/14/16  17:45:00                     20
5/14/16  17:45:02                  19.97
5/14/16  17:45:04                  19.97
5/14/16  17:45:06                  19.97
5/14/16  17:45:08                  19.97
5/14/16  17:45:10                     20
5/14/16  17:45:12                     20
5/14/16  17:45:14                     20
5/14/16  17:45:16                  19.97
5/14/16  17:45:18                  19.97
5/14/16  17:45:20                  19.97
5/14/16  17:45:22                     20
5/14/16  17:45:24                  19.97
5/14/16  17:45:26                  19.97
5/14/16  17:45:28                  19.97
5/14/16  17:45:30                  19.97
5/14/16  17:45:32                  19.97
5/14/16  17:45:34                  19.97
5/14/16  17:45:36                  19.97
5/14/16  17:45:38                  19.97
5/14/16  17:45:40                  19.97
5/14/16  17:45:42                  19.97
5/14/16  17:45:44                  19.97
5/14/16  17:45:46                  19.97
5/14/16  17:45:48                  19.97
5/14/16  17:45:50                  19.97
5/14/16  17:45:52                  19.97
5/14/16  17:45:54                  19.97
5/14/16  17:45:56                  19.97
...           ...                    ...
10/4/16  18:32:00                  14.04
10/4/16  18:32:02                  14.04
10/4/16  18:32:04                  14.04
10/4/16  18:32:06                  14.04
10/4/16  18:32:08                  14.04
10/4/16  18:32:10                  14.04
10/4/16  18:32:12                  14.04
10/4/16  18:32:14                  14.04
10/4/16  18:32:16                  14.04
10/4/16  18:32:18                  14.06
10/4/16  18:32:20                  14.06
10/4/16  18:32:22                  14.06
10/4/16  18:32:24                  14.06
10/4/16  18:32:26                  14.06
10/4/16  18:32:28                  14.06
10/4/16  18:32:30                  14.06
10/4/16  18:32:32                  14.06
10/4/16  18:32:34                  14.06
10/4/16  18:32:36                  14.06
10/4/16  18:32:38                  14.06
10/4/16  18:32:40                  14.06
10/4/16  18:32:42                  14.06
10/4/16  18:32:44                  14.06
10/4/16  18:32:46                  14.06
10/4/16  18:32:48                  14.09
10/4/16  18:32:50                  14.09
10/4/16  18:32:52                  14.09
10/4/16  18:32:54                  14.09
10/4/16  18:32:56                  14.09
10/4/16  18:32:58                  14.09

[825121 rows x 2 columns]

In [7]:
dfnew.to_csv('Multi-GAS_instemp_data.csv')